### ISSUE TITLE
Update README.md with setup procedure

### ISSUE THREAD

**Issue by compostbrain** [rubyforgood/demand-progress#12]

**Comment by jaydorsey** [comment]
Include:

- Getting a ProPublica API key
- Running the `rake committees:senate:load` and `rake committees:house:load` steps (maybe move this into a seed file instead?)

**Comment by colinxfleming** [comment]
I'm happy to take a stab at this! LMK if you want a docker build for this, I'm happy to do that too (in a separate PR). @duaimei
