### ISSUE TITLE
Investigate using propublica api to access congressional hearing data

### ISSUE THREAD

**Issue by compostbrain** [rubyforgood/demand-progress#16]
see here for more [details:](https://projects.propublica.org/api-docs/congress-api/committees/#get-recent-committee-hearings)

Here is a command that can be used:
```
curl "https://api.propublica.org/congress/v1/115/committees/hearings.json"
  -H "X-API-Key: PROPUBLICA_API_KEY"```

**Comment by crawfoal** [comment]
Done. We can use the following: 

```
curl "https://api.propublica.org/congress/v1/115/{senate|house}/committees/hearings.json?query=xx"
  -H "X-API-Key: PROPUBLICA_API_KEY"
```

where you choose either house or senate and `xx` is a multiple of 20 (give you the page).
